#!/usr/bin/env python3

"""
Created on 18 Dec 2025

@author: Bruno Beloff (bbeloff@me.com)

source repo: mrcs_cli

DESCRIPTION
A tool for managing security tokens for MRCS API sessions.
A username (email address) can be set for use in creating sessions.
The password should normally be given interactively when the session is created. An option that hard-codes the email
and password is included for end-to-end testing.

SYNOPSIS
usage: mrcs_session [-h] [-i INDENT] [-v] [--version] (-s SET_EMAIL | -e | -n | -c EMAIL PASSWORD | -d)

EXAMPLES
mrcs_session -s bbeloff1@me.com
mrcs_session -i

FILES
~/MRCS/conf/credentials.json
~/MRCS/conf/token.json
"""

import sys

import httpx

from mrcs_cli.cli.args.session_args import SessionArgs
from mrcs_cli.conf.client_token import ClientJWT
from mrcs_cli.conf.credentials import Credentials
from mrcs_cli.exceptions import HTTPResponseException
from mrcs_core.data.datum import Datum
from mrcs_core.sys.host import Host
from mrcs_core.sys.logging import Logging
from mrcs_core.sys.server import Server
from mrcs_core.sys.stdio import StdIO


# --------------------------------------------------------------------------------------------------------------------

if __name__ == '__main__':

    username = None
    password = None

    # ----------------------------------------------------------------------------------------------------------------

    args = SessionArgs('a tool for managing security tokens for MRCS API sessions')

    Logging.config('mrcs_session', verbose=args.verbose)
    logger = Logging.getLogger()
    logger.info(f'args: {args}')

    server = Server.load(Host, name='api')

    if not server:
        logger.error('server not configured.')
        exit(1)

    endpoint = server.url(path='/session')
    logger.info(f'endpoint: {endpoint}')

    # ----------------------------------------------------------------------------------------------------------------

    try:
        if args.set_email:
            if not Datum.is_email_address(args.set_email):
                logger.error(f'the email address {args.set_email} is not valid.')
                exit(2)

            credentials = Credentials(args.set_email, None)
            credentials.save(Host)
            exit(0)

        if args.erase_email:
            Credentials.delete(Host)
            exit(0)

        if args.credentials:
            username = args.email
            password = args.password

        if args.interactive:
            credentials = Credentials.load(Host)
            username = credentials.username if credentials else None
            username = StdIO.prompt('username', default=username)
            password = StdIO.password('password')

        if args.create_session:
            form = Credentials(username, password).as_form()

            try:
                response = httpx.post(endpoint, data=form)
                HTTPResponseException.check(response, 201)

                token = ClientJWT.construct_from_jdict(response.json())
                token.save(Host)
                exit(0)

            except httpx.ConnectError as ce:
                logger.error(f'{ce} - is the API server running?')

            except Exception as ex:
                logger.error(f'{ex.__class__.__name__}: {ex}')
                exit(1)

        if args.delete_session:
            ClientJWT.delete(Host)
            exit(0)

    # ----------------------------------------------------------------------------------------------------------------

    except KeyboardInterrupt:
        print(file=sys.stderr)
