#!/usr/bin/env python3

"""
Created on 26 Dec 2025

@author: Bruno Beloff (bbeloff@me.com)

source repo: mrcs_cli

DESCRIPTION
A tool for managing model time.
* Clock speed is a simple multiplier, a value of 1 indicates that the clock will run at natural speed
* Any combination of time offsets can be used - the default value for each is the current datetime
* Deleting the clock configuration will return the clock to natural time
The timezone of model time is the same timezone as the host processor.

Similar functionality is available from the mrcs_control/mrcs_clock utility. To clarify:

mrcs_cli/mrcs_time
* Intended for use when the system is running
* Mimics the functionality of the Web UI
* Requires the API server and mrcs_control/mrcs_clock_manager to be running in order to operate

mrcs_control/mrcs_clock
* Intended for use during system startup under systemd control
* Requires the mrcs_control/mrcs_clock_manager to be running in order to operate

A session must have been established with the API server, using the mrcs_session utility.
A 401 response typically indicates that the session token has expired.

SYNOPSIS
mrcs_cli_time [-h] [-i INDENT] [-v] [--version] (-n | -c | -s | -r | -d)
[-sr] [-ss SPEED] [-sy YEAR] [-sm MONTH] [-sd DAY] [-sh HOUR] [-si MINUTE]

EXAMPLES
mrcs_cli_time -vi4 -s -sr -ss 4 -sy 1930 -sm 1 -sd 2 -sh 6
mrcs_cli_time -n

SEE ALSO
mrcs_session
mrcs_control/mrcs_clock
"""

import sys

import httpx

from mrcs_cli.cli.args.time_args import TimeArgs
from mrcs_cli.conf.client_token import ClientJWT
from mrcs_cli.exceptions import HTTPResponseException
from mrcs_core.data.json import JSONify
from mrcs_core.sys.host import Host
from mrcs_core.sys.logging import Logging
from mrcs_core.sys.server import Server


# --------------------------------------------------------------------------------------------------------------------

if __name__ == '__main__':

    # ----------------------------------------------------------------------------------------------------------------

    args = TimeArgs('a tool for managing model time')

    Logging.config('mrcs_cli_time', verbose=args.verbose)
    logger = Logging.getLogger()
    logger.info(f'args: {args}')

    server = Server.load(Host, name='api')

    if not server:
        logger.error('server not configured.')
        exit(1)

    endpoint = server.url(path='/time')
    logger.info(f'endpoint: {endpoint}')

    token = ClientJWT.load(Host)
    if not token:
        logger.error('security token not set - use mrcs_session to create one.')
        exit(1)

    # ----------------------------------------------------------------------------------------------------------------

    try:
        if args.now:
            response = httpx.get(f'{endpoint}/now')
            HTTPResponseException.check(response, 200)

            print(JSONify.dumps(response.json()))
            exit(0)

        if args.conf:
            response = httpx.get(f'{endpoint}/conf')
            HTTPResponseException.check(response, 200)

            print(JSONify.dumps(response.json()))
            exit(0)

        if args.set:
            response = httpx.put(f'{endpoint}/set', headers=token.as_header(), json=args.clock_set())
            HTTPResponseException.check(response, 200)

            print(JSONify.dumps(response.json()))
            exit(0)

        if args.reload:
            response = httpx.patch(f'{endpoint}/reload', headers=token.as_header())
            HTTPResponseException.check(response, 200)

            print(JSONify.dumps(response.json()))
            exit(0)

        if args.delete:
            response = httpx.delete(f'{endpoint}/delete', headers=token.as_header())
            HTTPResponseException.check(response, 200)

            print(JSONify.dumps(response.json()))
            exit(0)

    # ----------------------------------------------------------------------------------------------------------------

    except httpx.ConnectError as ce:
        logger.error(f'{ce} - is the API server running?')
        exit(1)

    except HTTPResponseException as ex:
        logger.error(ex)
        exit(1)

    except KeyboardInterrupt:
        print(file=sys.stderr)
