#!/usr/bin/env python3

"""
Created on 18 Dec 2025

@author: Bruno Beloff (bbeloff@me.com)

source repo: mrcs_cli

DESCRIPTION
A tool for managing security tokens for MRCS API sessions.
A username (email address) can be set for use in creating sessions.
The password must be given interactively when the session is created.

SYNOPSIS
mrcs_session [-h] [-i INDENT] [-v] [--version] (-s SET_EMAIL | -e | -c | -d)

EXAMPLES
mrcs_session -s bbeloff1@me.com
mrcs_session -c
"""

import httpx
import sys

from http.client import HTTPException

from mrcs_cli.cli.args.session_args import SessionArgs
from mrcs_cli.conf.client_token import ClientJWT
from mrcs_cli.conf.credentials import Credentials
from mrcs_cli.conf.server import Server
from mrcs_core.data.datum import Datum

from mrcs_core.sys.host import Host
from mrcs_core.sys.logging import Logging
from mrcs_core.sys.stdio import StdIO


# --------------------------------------------------------------------------------------------------------------------

if __name__ == '__main__':

    # ----------------------------------------------------------------------------------------------------------------

    args = SessionArgs('a tool for managing security tokens for MRCS API sessions')

    Logging.config('mrcs_session', verbose=args.verbose)
    logger = Logging.getLogger()
    logger.info(f'args: {args}')

    server = Server.load(Host)

    if not server:
        logger.error('server not configured.')
        exit(1)

    endpoint = server.url('session')
    logger.info(f'endpoint: {endpoint}')


    # ----------------------------------------------------------------------------------------------------------------

    try:
        if args.set_email:
            if not Datum.is_email_address(args.set_email):
                logger.error(f'the email address {args.set_email} is not valid.')
                exit(2)

            credentials = Credentials(args.set_email, None)
            credentials.save(Host)
            exit(0)

        if args.erase_email:
            Credentials.delete(Host)
            exit(0)

        if args.create_session:
            credentials = Credentials.load(Host)
            username = credentials.username if credentials else None

            username = StdIO.prompt('username', default=username)
            password = StdIO.password('password')

            form = Credentials(username, password).as_form()

            try:
                response = httpx.post(endpoint, data=form)
                if response.status_code != 201:
                    raise HTTPException(f'{response.status_code}:{response.reason_phrase}')

                token = ClientJWT.construct_from_jdict(response.json())
                token.save(Host)
                exit(0)

            except Exception as ex:
                logger.error(f'{ex.__class__.__name__}: {ex}')
                exit(1)

        if args.delete_session:
            ClientJWT.delete(Host)
            exit(0)

    # ----------------------------------------------------------------------------------------------------------------

    except KeyboardInterrupt:
        print(file=sys.stderr)
