#!/usr/bin/env python3

"""
Created on 11 Dec 2025

@author: Bruno Beloff (bbeloff@me.com)

source repo: mrcs_cli

DESCRIPTION
A tool for publishing messages.
Message bodies are read from stdin or from the --message argument. Messages are published with source and target
routing specified by command-line arguments.

SYNOPSIS
mrcs_session [-h] [-i INDENT] [-v] [--version] (-e SET_EMAIL | -r REMOVE_EMAIL | -c CREATE | -d DELETE)

EXAMPLES

"""

import httpx
import json
import sys

from http.client import HTTPException
from json import JSONDecodeError

from mrcs_cli.cli.args.session_args import SessionArgs
from mrcs_cli.conf.credentials import Credentials
from mrcs_cli.conf.server import Server

from mrcs_core.data.datum import Datum
from mrcs_core.data.equipment_identity import EquipmentType, EquipmentIdentifier, EquipmentFilter
from mrcs_core.data.json import JSONify
from mrcs_core.messaging.message import Message
from mrcs_core.messaging.routing_key import PublicationRoutingKey
from mrcs_core.sys.host import Host
from mrcs_core.sys.logging import Logging
from mrcs_core.sys.stdio import StdIO


# TODO: maybe have a non-interactive mode, in which the credentials are provided on stdin?

# --------------------------------------------------------------------------------------------------------------------

if __name__ == '__main__':

    # ----------------------------------------------------------------------------------------------------------------

    args = SessionArgs('a tool for managing MRCS API sessions')

    Logging.config('mrcs_session', verbose=args.verbose)
    logger = Logging.getLogger()
    logger.info(f'args: {args}')

    server = Server.load(Host)

    if not server:
        logger.error('server not configured.')
        exit(1)

    endpoint = server.url('session')
    logger.info(f'endpoint: {endpoint}')


    # ----------------------------------------------------------------------------------------------------------------

    try:
        if args.set_email:
            # TODO: test whether email is valid
            credentials = Credentials(args.set_email, None)
            credentials.save(Host)
            exit(0)

        if args.erase_email:
            Credentials.delete(Host)
            exit(0)

        if args.create:
            credentials = Credentials.load(Host)
            username = credentials.username if credentials else None

            username = StdIO.prompt('username', default=username)
            password = StdIO.password('password')

            form = Credentials(username, password).as_form()

            try:
                response = httpx.post(endpoint, data=form)
                print(f'response: {response.content}')
                if response.status_code != 201:
                    raise HTTPException(f'{response.status_code}:{response.reason_phrase}')

                # TODO: save token

            except Exception as ex:
                logger.error(f'{ex.__class__.__name__}: {ex}')
                exit(1)


    # ----------------------------------------------------------------------------------------------------------------

    except KeyboardInterrupt:
        print(file=sys.stderr)
