#!/usr/bin/env python3

"""
Created on 6 Dec 2025

@author: Bruno Beloff (bbeloff@me.com)

source repo: mrcs_cli

DESCRIPTION
Configure the CLI client for the MRCS API server base URL. Required for correct functioning of the CLI utilities.

SYNOPSIS
mrcs_api_server [-h] [-i INDENT] [-v] [--version] [-s HOST PORT IS_SECURE]

EXAMPLES
mrcs_api_server -v -i4 -s localhost 8000 0

DOCUMENT EXAMPLE
{
    "host": "localhost",
    "port": 8000,
    "is_secure": false
}

FILES
~/MRCS/conf/api_server.json
"""

from mrcs_cli.cli.args.server_args import ServerArgs
from mrcs_core.data.json import JSONify
from mrcs_core.sys.host import Host
from mrcs_core.sys.logging import Logging
from mrcs_core.sys.server import Server


# --------------------------------------------------------------------------------------------------------------------

if __name__ == '__main__':

    name = 'api'
    publisher = None

    # ----------------------------------------------------------------------------------------------------------------

    args = ServerArgs('configure the CLI client for the MRCS API server base URL')

    Logging.config('mrcs_api_server', verbose=args.verbose)
    logger = Logging.getLogger()
    logger.info(f'args: {args}')

    if not args.is_valid():
        logger.error('invalid parameter(s)')
        exit(2)

    # ----------------------------------------------------------------------------------------------------------------

    if args.do_set:
        server = Server(args.host, args.port, args.is_secure, name=name)
        server.save(Host)

    server = Server.load(Host, name=name)
    print(JSONify.dumps(server, indent=args.indent))
