#!/usr/bin/env python3

"""
Created on 11 Dec 2025

@author: Bruno Beloff (bbeloff@me.com)

source repo: mrcs_cli

DESCRIPTION
A tool for publishing messages.
Message bodies are read from stdin or from the --message argument. Messages are published with source and target
routing specified by command-line arguments.

A session must have been established with the API server, using the mrcs_session utility.
A 401 response typically indicates that the session token has expired.

SYNOPSIS
mrcs_publisher [-h] [-i INDENT] [-v] [--version] [-s SOURCE_SERIAL]
[-t TARGET_TYPE] [-b TARGET_BLOCK] [-n TARGET_SERIAL] [-m MESSAGE_BODY]

EXAMPLES
mrcs_publisher -v -t MPU -b 1 -n 2

SEE ALSO
mrcs_session
"""

import httpx
import json
import sys

from http.client import HTTPException
from json import JSONDecodeError

from mrcs_cli.cli.args.publisher_args import PublisherArgs
from mrcs_cli.conf.client_token import ClientJWT
from mrcs_cli.conf.server import Server

from mrcs_core.data.datum import Datum
from mrcs_core.data.equipment_identity import EquipmentType, EquipmentIdentifier, EquipmentFilter
from mrcs_core.data.json import JSONify
from mrcs_core.messaging.message import Message
from mrcs_core.messaging.routing_key import PublicationRoutingKey
from mrcs_core.sys.host import Host
from mrcs_core.sys.logging import Logging


# --------------------------------------------------------------------------------------------------------------------

def publish_message(body):
    try:
        message = Message(routing_key, json.loads(body))
        logger.info(JSONify.as_jdict(message, indent=args.indent))

    except JSONDecodeError as jde:
        logger.error(f'{jde.__class__.__name__}: {body}')
        exit(2)

    try:
        response = httpx.post(endpoint, headers=token.as_header(), json=JSONify.as_jdict(message))
        if response.status_code != 200:
            raise HTTPException(f'{response.status_code}:{response.reason_phrase}')

    except Exception as ex:
        logger.error(f'{ex.__class__.__name__}: {ex}')
        exit(1)


# --------------------------------------------------------------------------------------------------------------------

if __name__ == '__main__':

    # ----------------------------------------------------------------------------------------------------------------

    args = PublisherArgs('a tool for publishing messages via the MRCS API')

    Logging.config('mrcs_publisher', verbose=args.verbose)
    logger = Logging.getLogger()
    logger.info(f'args: {args}')

    server = Server.load(Host)
    if not server:
        logger.error('server not configured.')
        exit(1)

    endpoint = server.url('tst/publish')
    logger.info(f'endpoint: {endpoint}')

    token = ClientJWT.load(Host)
    if not token:
        logger.error('security token not configured - use mrcs_session to create one.')
        exit(1)

    try:
        target = EquipmentFilter.construct(args.target_type, args.target_block, args.target_serial)
    except ValueError as ve:
        logger.error(ve)
        exit(2)


    # ----------------------------------------------------------------------------------------------------------------

    try:
        source = EquipmentIdentifier(EquipmentType.TST, None, args.source_serial)
        routing_key = PublicationRoutingKey(source, target)

        if args.message_body:
            publish_message(args.message_body)

        else:
            for message_body in Datum.effective_lines(sys.stdin):
                publish_message(message_body)


    # ----------------------------------------------------------------------------------------------------------------

    except KeyboardInterrupt:
        print(file=sys.stderr)
