#!/usr/bin/env python3

"""
Created on 6 Dec 2025

@author: Bruno Beloff (bbeloff@me.com)

source repo: mrcs_cli

DESCRIPTION
Configure the MRCS local web server base URL

SYNOPSIS
mrcs_server [-h] [-t] [-i INDENT] [-v] [--version] [-s HOST PORT IS_SECURE]

EXAMPLES
mrcs_server -v -i4 -s 127.0.0.1 8080 0

DOCUMENT EXAMPLE
{
    "host": "127.0.0.1",
    "port": 8000,
    "is_secure": false
}
"""

from mrcs_cli.cli.args.server_args import ServerArgs
from mrcs_cli.sys.server import Server

from mrcs_core.data.json import JSONify
from mrcs_core.sys.host import Host
from mrcs_core.sys.logging import Logging


# --------------------------------------------------------------------------------------------------------------------

if __name__ == '__main__':

    publisher = None

    # ----------------------------------------------------------------------------------------------------------------

    args = ServerArgs('configure the MRCS local web server base URL')

    Logging.config('mrcs_server', verbose=args.verbose)
    logger = Logging.getLogger()
    logger.info(f'args: {args}')

    if not args.is_valid():
        logger.error('invalid parameter(s)')
        exit(2)


    # ----------------------------------------------------------------------------------------------------------------

    if args.do_set:
        server = Server(args.host, args.port, args.is_secure)
        server.save(Host)

    server = Server.load(Host)
    print(JSONify.dumps(server, indent=args.indent))
