#!/usr/bin/env python3

"""
Created on 20 Dec 2025

@author: Bruno Beloff (bbeloff@me.com)

source repo: mrcs_cli

DESCRIPTION
A tool for listing the latest N logged messages via the MRCS API.

A session must have been established with the API server, using the mrcs_session utility.
A 401 response typically indicates that the session token has expired.

SYNOPSIS
mrcs_messages [-h] [-i INDENT] [-v] [--version] -l LIST

EXAMPLES
mrcs_messages -vi4 -l 10

SEE ALSO
mrcs_session
"""

import httpx
import sys

from mrcs_cli.cli.args.messages_args import MessagesArgs
from mrcs_cli.conf.client_token import ClientJWT
from mrcs_cli.conf.server import Server
from mrcs_cli.exceptions import HTTPResponseException

from mrcs_core.data.json import JSONify
from mrcs_core.operations.recorder.message_record import MessageRecord
from mrcs_core.sys.host import Host
from mrcs_core.sys.logging import Logging


# --------------------------------------------------------------------------------------------------------------------

if __name__ == '__main__':

    # ----------------------------------------------------------------------------------------------------------------

    args = MessagesArgs('a tool for listing logged messages via the MRCS API')

    Logging.config('mrcs_users', verbose=args.verbose)
    logger = Logging.getLogger()
    logger.info(f'args: {args}')

    server = Server.load(Host)
    if not server:
        logger.error('server not configured.')
        exit(1)

    endpoint = server.url('mlg')
    logger.info(f'endpoint: {endpoint}')

    token = ClientJWT.load(Host)
    if not token:
        logger.error('security token not configured - use mrcs_session to create one.')
        exit(1)

    # ----------------------------------------------------------------------------------------------------------------

    try:
        response = httpx.get(f'{endpoint}/latest', headers=token.as_header(), params={"limit": args.list})
        HTTPResponseException.check(response, 200)

        users = [MessageRecord.construct_from_jdict(jdict) for jdict in response.json()]
        print(JSONify.dumps(users, indent=args.indent))

    # ----------------------------------------------------------------------------------------------------------------

    except HTTPResponseException as ex:
        logger.error(ex)

    except KeyboardInterrupt:
        print(file=sys.stderr)
